[package]
name = "libm8"
version = "0.1.0"
edition = "2024"

[lib]
name = "m8"
crate-type = ["cdylib", "rlib"]

[dependencies]
cpal = { version = "0.18.1", features = ["pipewire", "asio"] }
sdl3 = { version = "0.17.0", features = ["build-from-source-static"] }
enum-map = "2.7.3"
ringbuf = "0.4.8"
serialport = "4.8.1"
spectrum-analyzer = "1.7.0"
thiserror = "2.0.17"

godot = { version = "0.5.4", features = ["register-docs"], optional = true }

[features]
gdext = ["dep:godot"]
