name: Build GDExtension
on:
  workflow_call:
  push:
  pull_request:
  merge_group:

env:
  BIN_NAME: m8gd
  LIB_NAME: libm8

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            arch: x86_64
            os: ubuntu-24.04

          - platform: windows
            arch: x86_64
            os: windows-latest

          - platform: macos
            arch: universal
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Linux Dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config
          sudo apt-get install pkg-config cmake ninja-build libasound2-dev libpulse-dev \
          libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev \
          libpipewire-0.3-dev libspa-0.2-dev

      - uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rust -> rust/target"

      - name: Cache Build Artifacts
        uses: actions/cache@v4
        with:
          path: build/
          key: ${{ matrix.platform }}-build

      - name: Compile Debug
        shell: bash
        run: python build.py gdext
        env:
          RUSTFLAGS: "-Awarnings"

      - name: Compile Release and Export Godot Project
        shell: bash
        run: python build.py gui --release
        env:
          RUSTFLAGS: "-Awarnings"

      - name: Upload Artifact (Export)
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.BIN_NAME }}-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            ${{ github.workspace }}/build/gui/*

      - name: Copy License File
        shell: bash
        run: cp LICENSE godot/addons/libm8/LICENSE

      - name: Upload Artifact (Addon)
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.LIB_NAME }}-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            ${{ github.workspace }}/godot/addons/libm8/*

  merge:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Merge Addon Files
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ env.LIB_NAME }}
          pattern: ${{ env.LIB_NAME }}*
